name       : gimp-plugin-beautify
version    : 0.5.3
release    : 1
source     :
    - https://github.com/hejiann/beautify/archive/v0.5.3.tar.gz : 7a5d86c9d581e8c1ee28e0ae2cb794b216ac85ad5b6c0e8020e3c959309e1df2
license    : GPL-3.0
component  : multimedia.graphics
summary    : GIMP Beautify is a set of GIMP plug-ins for quickly and easily beautify photo 
description: |
    GIMP Beautify is a set of GIMP plug-ins for quickly and easily beautify photo.
builddeps  :
    - pkgconfig(gimp-2.0)
rundeps :
    - gimp
setup      : |
build      : |
    %make
install    : |
    install -dm755 $installdir/usr/lib/gimp/2.0/plug-ins/
    install -Dm 755 beautify $installdir/usr/lib/gimp/2.0/plug-ins/beautify
    install -Dm 755 skin-whitening $installdir/usr/lib/gimp/2.0/plug-ins/skin-whitening
    install -Dm 755 simple-border $installdir/usr/lib/gimp/2.0/plug-ins/simple-border
    install -Dm 755 border $installdir/usr/lib/gimp/2.0/plug-ins/border
