name       : gimp-lensfun
version    : 0.2.4
release    : 1
source     :
    - https://github.com/seebk/GIMP-Lensfun/archive/0.2.4.tar.gz : 7a4e6dade910952cdb9afc62f34e286d230dd73c3a1630415c106b5260eb94de
license    : GPL-3.0
component  : multimedia.graphics
summary    : GIMP plugin for correcting lens distortion using the lensfun library and database
description: |
    GIMP plugin for correcting lens distortion using the lensfun library and database.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gimp-2.0)
    - pkgconfig(lensfun)
rundeps :
    - gimp
    - lensfun
setup      : |
build      : |
    %make
install    : |
    install -D -Dm 755 gimp-lensfun $installdir/usr/lib/gimp/2.0/plug-ins/gimp-lensfun
    install -D -m0644 CHANGES.txt $installdir/usr/share/doc/gimp-lensfun/CHANGES.txt
    install -D -m0644 LICENSE.txt $installdir/usr/share/doc/gimp-lensfun/LICENSE.txt
    install -D -m0644 README.txt $installdir/usr/share/doc/gimp-lensfun/README.txt
