name       : spice-up
version    : 1.0.1
release    : 2
source     :
    - https://github.com/Philip-Scott/Spice-up/archive/1.0.1.tar.gz : 2d2a598c9b61ff0ae11b73709957cda18c82879181c986219bb07dbca89b5054
license    : GPL-3.0
component  : office
summary    : Create Simple and Beautiful presentations
description: |
    Spice-up is a modern and intuitive desktop presentation app based upon SpiceOfDesign's presentation concept.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(gudev-1.0)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install


