name       : duckietv
version    : 1.1.5
release    : 1
source     :
    - https://github.com/SchizoDuckie/DuckieTV/releases/download/1.1.5/DuckieTV-1.1.5-linux-x64.tar.gz : ded2eb377c8730adb74f0248c786fc35bee0503f193c6ef42b77c11c1b89a92c
license    : MIT
component  : network.web
summary    : A personalized calendar that tracks the shows you like
description: |
    DuckieTV is an application that takes care of TV-Show addicts by providing a personalized TV-Show calendar.
rundeps  :
    - nodejs
setup      : |
build      : | 
install    : |
    install -d $installdir/opt
    mkdir -p $installdir/opt
    cd $workdir
    cp -r ../DuckieTV $installdir/opt/
    mkdir -p "$installdir"/usr/share/applications
    cp ../share/applications/DuckieTV.desktop $installdir/usr/share/applications
    mkdir -p $installdir/usr/bin/
    ln -s /opt/DuckieTV/DuckieTV $installdir/usr/bin/DuckieTV
    mkdir -p $installdir/usr/share/pixmaps
    cp ../share/pixmaps/DuckieTV.xpm $installdir/usr/share/pixmaps
