name       : tootle
version    : 0.1.3
release    : 1
source     :
    - https://github.com/bleakgrey/tootle/archive/0.1.3.tar.gz : d0462237e09f70bfbb19b0ba4f8471b3e6d6a2cb11f6dd8132f095954238e323
license    : GPL-3.0
component  : network
summary    : GTK3 client for Mastodon 
description: |
    GTK3 client for Mastodon  
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
