name       : playmymusic
version    : 0.6.7
release    : 1
source     :
    - https://github.com/artemanufrij/playmymusic/archive/0.6.7.tar.gz : e2657afeb96cdd37d6157dda76bbdf510c445b8365ec907bd462487543c133ef
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A music player for listening to local music files, online radios, and Audio CD's
description: |
    A music player for listening to local music files, online radios, and Audio CD's
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - vala
setup      : |
    %apply_patches
    mkdir cmake
    install -m 00644 $pkgfiles/cmake/*.cmake cmake/.
    %cmake .
build      : |
    %make
install    : |
    %make_install
