name       : tutrl
version    : 0.6.4
release    : 1
source     :
    -  https://turtl.it/releases/desktop/turtl-linux64-0.6.4.tar.bz2 : bb4708a0d5969a9fe832fd76a8aeca0050055c1c551eeaad130b7f1e392e8241
license    : GPL-3
component  : desktop
summary    : Turtl lets you take notes, bookmark websites, and store documents for sensitive projects.
description: |
    Turtl lets you take notes, bookmark websites, and store documents for sensitive projects.
builddeps  :
    - glibc
build      : |
install    : |
    cd $workdir
    mkdir -p $installdir/opt/turtl
    mkdir -p $installdir/usr/bin
    ./install.sh $installdir/opt/turtl > /dev/null
    rm -f "$HOME/.local/share/applications/turtl.desktop" > /dev/null
    install -Dm644 "$pkgfiles/turtl.desktop" "$installdir/usr/share/applications/turtl.desktop"
    install -Dm644 $workdir/turtl/icon.png "$installdir/usr/share/pixmaps/turtl.png"
    ln -s "/opt/turtl/turtl" "$installdir/usr/bin/turtl"
    chmod +r -R "$installdir/opt/turtl/"
    chmod +rx "$installdir/opt/turtl/turtl" "$installdir/opt/turtl/turtl-bin" \
    "$installdir/opt/turtl/chromedriver" \
    "$installdir/opt/turtl/nwjc" $installdir/opt/turtl/nacl* \
    "$installdir/opt/turtl/payload" "$installdir/opt/turtl/lib" \
    "$installdir/opt/turtl/locales" "$installdir/opt/turtl/pnacl"

