name       : frogr
version    : 1.3
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/frogr/1.3/frogr-1.3.tar.xz : 94cc6a7ab2553e00cc8e0c2435a1c2610de0fc59ce51e78fe0d758f34d5c7a36
license    : GPL-3.0
component  : multimedia.graphics
summary    : A flickr remote organizer for GNOME
description: |
    Frogr is a small application for the GNOME desktop that allows users to manage their accounts in the Flickr image hosting website. It supports all the basic Flickr features, including uploading pictures, adding descriptions, setting tags and managing sets and groups pools.
builddeps  :
    - itstool
rundeps :
    - exiv2
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

