name       : flameshot
version    : 0.5.0
release    : 1
source     :
    - https://github.com/lupoDharkael/flameshot/archive/v0.5.0.tar.gz : 32d593c14c37286d9f64873c4ef9a07eb084723c92b2280d5c22152547c1e3f0
license    : GPL-3.0
component  : desktop
summary    : Powerful yet simple to use screenshot software
description: |
    Powerful yet simple to use screenshot software.
builddeps  :
    - pkgconfig(Qt5UiTools)
rundeps :
    - exiv2
setup      : |
    %qmake
build      : |
    %make
install    : |
    install -Dm755 "./flameshot" "$installdir/usr/bin/flameshot"
    install -Dm644 "./dbus/package/org.dharkael.Flameshot.service" "$installdir/usr/share/dbus-1/services/org.dharkael.Flameshot.service"
    install -Dm644 "./dbus/org.dharkael.Flameshot.xml" "$installdir/usr/share/dbus-1/interfaces/org.dharkael.Flameshot.xml"
    install -Dm644 "./docs/desktopEntry/package/flameshot.desktop" "$installdir/usr/share/applications/flameshot.desktop"
    install -Dm644 "./docs/desktopEntry/package/flameshot-init.desktop" "$installdir/usr/share/applications/flameshot-init.desktop"
    install -Dm644 "./img/flameshot.png" "$installdir/usr/share/icons/flameshot.png"

