name       : bookworm
version    : 0.9.9
release    : 1
source     :
    - https://github.com/babluboy/bookworm/archive/0.9.9.tar.gz : a120d60281459c055bd4c444a7939248cfc2611396eabcc04768b391c702629c
license    : GPL-3.0
component  : office.viewers
summary    : A simple ebook reader
description: |
    Read the books you love without having to worry about the different format complexities like epub, pdf, mobi, cbr, etc. This version supports EPUB, PDF and Comics (CBR and CBZ) formats with support for more formats to follow soon.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(poppler-glib)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - poppler-utils
    - vala
setup      : |
build      : |
    %cmake
    %make
install    : |
    %make_install
