name       : slsk
version    : 1.3.1.1
release    : 1
source     :
    - https://github.com/supremesonicbrazil/SLSK/archive/v1.3.1.0.tar.gz : 19d00dfd545b056a56ec570ba32bfcdec57aeafd4c2b32c4c53ca5736546b425
license    : GPL-3.0
component  : games.platformer
summary    : Steam Linux Swiss Knife
description: |
    Steam Linux Swiss Knife - A backup utility and database for Linux Steam games 
rundeps  :
    - steam
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Widgets)
build      : |
    ./BUILD.sh
install    : |
    install -Dm755 ./bin/SteamLinuxSwissKnife "$installdir"/usr/bin/slsk
    install -Dm644 ./bin/SteamLinuxGames.db "$installdir"/usr/share/slsk/SteamLinuxGames.db
    install -Dm644 ./steam-linux-swiss-knife.desktop "$installdir"/usr/share/applications/steam-linux-swiss-knife.desktop
    cp -r ./img "$installdir"/usr/share/slsk
