name       : megasync
version    : 3.5.0.0
release    : 2
source     :
    - https://github.com/meganz/MEGAsync/archive/v3.5.0.0_Win.tar.gz : 09fccdabe2c16f877e68f40fbfc46d9c7ea1b8f6ea8b29dc10c92e1a5d1e2d90
    - https://github.com/meganz/sdk/archive/v3.2.7.tar.gz: fc0bab64a45f01988b5c9956047f4e5037608ec7c39d6c2e661dfa33020c8ac1
license    : MEGA LIMITED CODE REVIEW LICENCE
component  : network.clients
summary    : Sync your files to your Mega account.
description: |
    Easy automated syncing between your computers and your MEGA Cloud Drive.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(libuv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - cryptopp-devel
setup      : |
    cd $workdir/src/MEGASync/mega
    tar -xf $sources/v3.2.7.tar.gz --strip 1 -C .
    %autogen --without-freeimage
    cd $workdir/src
    %configure
build      : |
    cd $workdir/src
    %qmake MEGA.pro
    lrelease MEGASync/MEGASync.pro
    %make
install    : |
    install -Dm 644 $workdir/LICENCE.md $installdir/usr/share/licenses/megasync/LICENCE.md
    install -Dm 644 $workdir/installer/terms.txt $installdir/usr/share/licenses/megasync/terms.txt
    install -Dm 755 $workdir/src/MEGASync/megasync $installdir/usr/bin/megasync
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/megasync.desktop $installdir/usr/share/applications/megasync.desktop
    for size in 16x16 32x32 48x48 128x128 256x256
    do
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/icons/hicolor/$size/apps/mega.png $installdir/usr/share/icons/hicolor/$size/apps/mega.png
    done
