name       : budgie-extra
version    : 0.5.0
release    : 1
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/archive/v0.5.0.tar.gz : ced39bf827795b88bc60d280c01233079ebd3e2519bbccd7646a5459842fc005
license    : GPL-3-or-later
summary    : additional Budgie Desktop enhancements for the user experience
component  : desktop.budgie
builddeps  :
    - meson
rundeps  :
    - budgie-desktop
    - python3-pyudev
    - xinput
    - xrandr
    - xprop
description: |
    additional Budgie Desktop enhancements for the user experience
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
